//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraverReserveCL
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.UserTicket = new HashSet<UserTicket>();
        }
        [DataMember(Order = 1)]
        public int Id { get; set; }
        [DataMember(Order = 2)]
        public int TripId { get; set; }
        [DataMember(Order = 3)]
        public decimal Price { get; set; }
        [DataMember(Order = 4)]
        public System.DateTime FromDate { get; set; }
        [DataMember(Order = 5)]
        public Nullable<System.DateTime> ToDate { get; set; }
        [DataMember(Order = 6)]
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember(Order = 7)]
        public virtual ICollection<UserTicket> UserTicket { get; set; }
    }
}
