//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelReserveDataProvider.Models
{
    using TravelReserveCL;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BusTravelEntities : DbContext
    {
        public BusTravelEntities()
            : base("name=BusTravelEntities")
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> Bus { get; set; }
        public virtual DbSet<BusStation> BusStation { get; set; }
        public virtual DbSet<BusType> BusType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserPlan> UserPlan { get; set; }
        public virtual DbSet<UserTicket> UserTicket { get; set; }
    }
}
